#!/bin/bash

# base del comando https://gist.github.com/irazasyed/a7b0a079e7727a4315b9

# PATH TO YOUR HOSTS FILE
ETC_HOSTS=/etc/hosts


# Pregunta si quiere añadir o eliminar

echo "¿Quieres añadir o eliminar el hostname?(poner/quitar):" 
read respuestahost

clear
# muestra el archivo hosts y pausa la pantalla durante 3 segundos
cat $ETC_HOSTS
sleep 3

# si quiere poner pide IP y nombre, si quiere borrar solo el nombre.
if [ $respuestahost = poner ]
	then
# pide IP
echo -n "¿Que IP quieres asignar al nuevo host?:"  
read newip4hn
IP=$newip4hn
# pide nombre
echo -n introduce nuevo nombre de host: 
read newhn
	else
# Si dice quitar solo pide nombre 
echo -n introduce nuevo nombre de host: 
read newhn
fi
# Hostname para  add/remove.
HOSTNAME=$newhn

#funcion de eliminar
removehost() {
    echo "Eliminando host";
    if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
    then
        echo "$HOSTNAME encontrado en tu $ETC_HOSTS, eliminando...";
        sudo sed -i".bak" "/$HOSTNAME/d" $ETC_HOSTS
    else
        echo "$HOSTNAME no ha sido encontrado en tu $ETC_HOSTS";
    fi
}

addhost() {
    echo "añadiendo host";
    HOSTS_LINE="$IP\t$HOSTNAME"
    if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
        then
            echo "$HOSTNAME ya existe : $(grep $HOSTNAME $ETC_HOSTS)"
        else
            echo "añadiendo $HOSTNAME en tu $ETC_HOSTS";
            sudo -- sh -c -e "echo '$HOSTS_LINE' >> /etc/hosts";

            if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
                then
                    echo "$HOSTNAME se ha añadido correctamente \n $(grep $HOSTNAME /etc/hosts)";
                else
                    echo "Error al añadir $HOSTNAME, intentalo de nuevo!";
            fi
    fi
}

# ejecuta las funciones
if [ $respuestahost = poner ]
	 then
addhost
	else 
removehost
fi
